mod actions;
mod bar;
mod config;
mod groups;
mod menu;
mod theme;
mod tmux;

use std::os::unix::process::CommandExt;
use std::process::Command;

use actions::{cmd_new, cmd_nth, cmd_status, load_snapshot, save_snapshot};
use bar::{cmd_click, cmd_click_close, cmd_render, cmd_render_msgs};
use config::{apply_all_layouts, apply_layout, reset_global, setup_done, tmux_status_block};
use groups::{close_group, ensure_group, group_of_session, last_used_member, list_groups, members_for, DEFAULT_GROUP};
use menu::{cmd_getting_started, cmd_menu};
use tmux::{conf_dir, conf_path, launcher, tmux, tmux_ok, tmux_stdout, SOCKET};

fn write_conf() {
    let _ = std::fs::create_dir_all(conf_dir());
    let exe = launcher().display().to_string();
    let mut nth = String::new();
    for i in 1..10 {
        nth.push_str(&format!(
            "bind-key {i} run-shell -C \"{exe} nth {i} '' #{{session_name}}\"\n"
        ));
    }
    let mut body = String::from(
        r###"# Generated by tabmux. Isolated server (tmux -L @SOCKET@).
set -g mouse on
set -g extended-keys on
set -g default-terminal "screen-256color"
unbind-key C-b
set -g prefix None
bind-key -n C-b display-popup -B -w 100% -h 100% -E "@EXE@ menu #{client_name}"
set -g status-interval 1
set -g status-style "bg=@INACTIVE_BG@,fg=@INACTIVE_FG@"
set -g status-left ""
set -g status-right ""
set -g status-left-length 0
set -g status-right-length 0
set -g window-status-format ""
set -g window-status-current-format ""
@STATUS_BLOCK@
set-hook -gu session-created
set-hook -g session-created "run-shell \"@EXE@ layout #{q:session_name}\""
set-hook -gu session-closed
set-hook -gu client-session-changed
set-hook -g client-detached "run-shell \"@EXE@ save\""

unbind-key -n MouseDown3StatusLeft
unbind-key -n MouseDown3StatusRight
bind-key -n MouseDown1Status run-shell "@EXE@ click #{mouse_x} #{client_width} #{client_name} #{mouse_status_line} #{session_name}"
bind-key -n MouseDown3Status run-shell "@EXE@ click-close #{mouse_x} #{client_width} #{client_name} #{mouse_status_line} #{session_name}"

@NTH@
"###,
    );
    body = body
        .replace("@SOCKET@", SOCKET)
        .replace("@EXE@", &exe)
        .replace("@INACTIVE_BG@", &crate::config::load_global().theme().inactive_bg)
        .replace("@INACTIVE_FG@", &crate::config::load_global().theme().inactive_fg)
        .replace("@MSG_BG@", &crate::config::load_global().theme().msg_bg)
        .replace("@STATUS_BLOCK@", &tmux_status_block(&exe))
        .replace("@NTH@", &nth);
    let _ = std::fs::write(conf_path(), body);
}

fn ensure_server(initial: &str) {
    write_conf();
    if tmux_ok(&["list-sessions"]) {
        let conf = conf_path().display().to_string();
        tmux(&["source-file", &conf]);
        apply_all_layouts();
        return;
    }
    let conf = conf_path().display().to_string();
    let snapshot = load_snapshot();
    let mut sessions = snapshot.into_iter();
    match sessions.next() {
        Some((name, path)) => {
            let _ = std::process::Command::new("tmux")
                .args(["-L", SOCKET, "-f", &conf, "new-session", "-d", "-s", &name, "-c", &path])
                .status();
            for (name, path) in sessions {
                if !tmux_ok(&["has-session", "-t", &format!("={name}")]) {
                    tmux(&["new-session", "-d", "-s", &name, "-c", &path]);
                }
            }
        }
        None => {
            let _ = std::process::Command::new("tmux")
                .args(["-L", SOCKET, "-f", &conf, "new-session", "-d", "-s", initial])
                .status();
        }
    }
    save_snapshot();
    apply_all_layouts();
}

fn inside_this_server() -> bool {
    std::env::var("TMUX")
        .map(|v| v.replace('\\', "/").contains(&format!("/{SOCKET},")))
        .unwrap_or(false)
}

fn cmd_attach(group: Option<&str>) {
    let group = group.filter(|s| !s.is_empty()).unwrap_or(DEFAULT_GROUP).to_string();
    if !setup_done() && unsafe { libc::isatty(0) } != 0 {
        cmd_getting_started();
    }
    ensure_server(&group);
    let members = ensure_group(&group);
    save_snapshot();
    let target = last_used_member(&members).unwrap_or_else(|| members[0].clone());
    if inside_this_server() {
        eprintln!("already inside tabmux ({SOCKET})");
        return;
    }
    let err = Command::new("tmux")
        .args(["-L", SOCKET, "attach-session", "-t", &format!("={target}")])
        .env_remove("TMUX")
        .exec();
    panic!("exec tmux: {err}");
}

fn cmd_ls() {
    let server_up = tmux_ok(&["list-sessions"]);
    let current = if server_up {
        tmux_stdout(&["display-message", "-p", "#{session_name}"])
            .trim()
            .to_string()
    } else {
        String::new()
    };
    let current_group = group_of_session(&current);
    for group in list_groups() {
        let mark = if Some(&group) == current_group.as_ref() { '*' } else { ' ' };
        let count = groups::group_members(&group).len();
        println!("{mark} {group:<16} {count} session{}", if count == 1 { "" } else { "s" });
    }
}

fn cmd_close_group(group: &str) {
    let killed = close_group(group);
    println!("closed {group} ({killed} session{})", if killed == 1 { "" } else { "s" });
}

fn usage() {
    print!(
        "\
tabmux — isolated tmux with a bottom session tab bar

Group sessions (each group is its own independent set of tabs):
  tabmux              attach to the default group
  tabmux attach [xx]  attach to group xx (no name = default)
  tabmux ls           list groups
  tabmux close <xx>   kill group xx and all its sessions
  tabmux status <name> [session]
                      set this tab's status dot (busy/attention/idle/unset or any name)
  tabmux save         write session names and cwd so a restart can recreate tabs
  tabmux config reset  clear global bar settings (getting started on next attach)

Inside the app: Ctrl-b for the command menu.
"
    );
}

fn opt(s: Option<&String>) -> Option<&str> {
    s.map(|s| s.as_str()).filter(|s| !s.is_empty())
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.is_empty() {
        cmd_attach(None);
        return;
    }
    let cmd = args[0].as_str();
    let rest = &args[1..];
    match cmd {
        "-h" | "--help" | "help" => usage(),
        "attach" => cmd_attach(opt(rest.first())),
        "render" => {
            let w = rest.first().and_then(|s| s.parse().ok()).unwrap_or(80);
            let cur = rest.get(1).map(|s| s.as_str()).unwrap_or("");
            cmd_render(w, cur);
        }
        "render-msgs" => {
            let w = rest.first().and_then(|s| s.parse().ok()).unwrap_or(80);
            let cur = rest.get(1).map(|s| s.as_str()).unwrap_or("");
            cmd_render_msgs(w, cur);
        }
        "click" => {
            let x = rest.first().and_then(|s| s.parse().ok()).unwrap_or(0);
            let w = rest.get(1).and_then(|s| s.parse().ok()).unwrap_or(80);
            let line = rest.get(3).and_then(|s| s.parse().ok()).unwrap_or(0);
            let current = rest.get(4).map(|s| s.as_str()).unwrap_or("");
            cmd_click(x, w, opt(rest.get(2)), line, current);
        }
        "click-close" => {
            let x = rest.first().and_then(|s| s.parse().ok()).unwrap_or(0);
            let w = rest.get(1).and_then(|s| s.parse().ok()).unwrap_or(80);
            let line = rest.get(3).and_then(|s| s.parse().ok()).unwrap_or(0);
            let current = rest.get(4).map(|s| s.as_str()).unwrap_or("");
            cmd_click_close(x, w, opt(rest.get(2)), line, current);
        }
        "new" => {
            cmd_new(
                rest.first().map(|s| s.as_str()).unwrap_or(""),
                opt(rest.get(1)),
                None,
            );
        }
        "close" => {
            let Some(group) = opt(rest.first()) else {
                eprintln!("tabmux close: missing group name");
                std::process::exit(2);
            };
            cmd_close_group(group);
        }
        "nth" => {
            let i = rest.first().and_then(|s| s.parse().ok()).unwrap_or(0);
            let current = rest.get(2).map(|s| s.as_str()).unwrap_or("");
            let names = members_for(current);
            cmd_nth(&names, i, opt(rest.get(1)));
        }
        "menu" => cmd_menu(opt(rest.first())),
        "ls" => cmd_ls(),
        "layout" => {
            let sess = rest.first().map(|s| s.as_str()).unwrap_or("");
            if sess.is_empty() {
                apply_all_layouts();
            } else {
                apply_layout(sess);
            }
        }
        "config" => match rest.first().map(|s| s.as_str()) {
            Some("reset") => {
                reset_global();
                println!("global config cleared; next attach runs getting started");
            }
            _ => {
                eprintln!("tabmux config reset");
                std::process::exit(2);
            }
        },
        "status" => {
            let Some(state) = rest.first() else {
                eprintln!("tabmux status: missing state (busy, attention, idle, or any name)");
                std::process::exit(2);
            };
            cmd_status(state, opt(rest.get(1)), None);
        }
        "save" => save_snapshot(),
        _ => {
            usage();
            std::process::exit(2);
        }
    }
}
