mod actions;
mod bar;
mod menu;
mod tmux;

use std::os::unix::process::CommandExt;
use std::process::Command;

use actions::{cmd_close, cmd_new, cmd_nth, cmd_rename};
use bar::{cmd_click, cmd_click_close, cmd_render, cmd_render_msgs};
use menu::cmd_menu;
use tmux::{
    conf_dir, conf_path, launcher, list_sessions, tmux, tmux_ok, tmux_stdout, INACTIVE_BG,
    INACTIVE_FG, MSG_BG, SOCKET,
};

fn write_conf() {
    let _ = std::fs::create_dir_all(conf_dir());
    let exe = launcher().display().to_string();
    let mut nth = String::new();
    for i in 1..10 {
        nth.push_str(&format!("bind-key {i} run-shell -C \"{exe} nth {i}\"\n"));
    }
    let mut body = String::from(
        r###"# Generated by tabmux. Isolated server (tmux -L @SOCKET@).
set -g mouse on
set -g extended-keys on
set -g default-terminal "screen-256color"
unbind-key C-b
set -g prefix None
bind-key -n C-b display-popup -B -w 100% -h 100% -E "@EXE@ menu #{client_name}"
set -g status 2
set -g status-position bottom
set -g status-interval 1
set -g status-style "bg=@INACTIVE_BG@,fg=@INACTIVE_FG@"
set -g status-left ""
set -g status-right ""
set -g status-left-length 0
set -g status-right-length 0
set -g window-status-format ""
set -g window-status-current-format ""
set -g status-format[0] "#[align=left fill=@INACTIVE_BG@]#(@EXE@ render #{client_width} #{q:session_name})"
set -g status-format[1] "#[align=left fill=@MSG_BG@]#(@EXE@ render-msgs #{client_width})"

set-hook -gu session-created
set-hook -gu session-closed
set-hook -gu client-session-changed

unbind-key -n MouseDown3StatusLeft
unbind-key -n MouseDown3StatusRight
bind-key -n MouseDown1Status run-shell "@EXE@ click #{mouse_x} #{client_width} #{client_name} #{mouse_status_line}"
bind-key -n MouseDown3Status run-shell "@EXE@ click-close #{mouse_x} #{client_width} #{client_name} #{mouse_status_line}"

@NTH@
"###,
    );
    body = body
        .replace("@SOCKET@", SOCKET)
        .replace("@EXE@", &exe)
        .replace("@INACTIVE_BG@", INACTIVE_BG)
        .replace("@INACTIVE_FG@", INACTIVE_FG)
        .replace("@MSG_BG@", MSG_BG)
        .replace("@NTH@", &nth);
    let _ = std::fs::write(conf_path(), body);
}

fn ensure_server() {
    write_conf();
    if tmux_ok(&["list-sessions"]) {
        let conf = conf_path().display().to_string();
        tmux(&["source-file", &conf]);
        return;
    }
    let conf = conf_path().display().to_string();
    let _ = std::process::Command::new("tmux")
        .args(["-L", SOCKET, "-f", &conf, "new-session", "-d", "-s", "main"])
        .status();
}

fn inside_this_server() -> bool {
    std::env::var("TMUX")
        .map(|v| v.replace('\\', "/").contains(&format!("/{SOCKET},")))
        .unwrap_or(false)
}

fn cmd_attach() {
    ensure_server();
    if inside_this_server() {
        eprintln!("already inside tabmux ({SOCKET})");
        return;
    }
    let err = Command::new("tmux")
        .args(["-L", SOCKET, "attach-session"])
        .env_remove("TMUX")
        .exec();
    panic!("exec tmux: {err}");
}

fn cmd_ls() {
    let names = list_sessions();
    let current = if names.is_empty() {
        String::new()
    } else {
        tmux_stdout(&["display-message", "-p", "#{session_name}"])
            .trim()
            .to_string()
    };
    for (i, name) in names.iter().enumerate() {
        let mark = if *name == current { '*' } else { ' ' };
        println!("{mark}{:>2}  {name}", i + 1);
    }
}

fn usage() {
    print!(
        "\
tabmux — isolated tmux with a bottom session tab bar

  tabmux              attach (creates server if needed)
  tabmux ls           list sessions
  tabmux new [name]        create and switch
  tabmux close [name]      kill session
  tabmux rename [old] <new>  rename a session (old defaults to current)

Inside the app:
  Ctrl-b                 command menu
  left-click tab         switch
  right-click tab        close
  n                      new session
  r                      rename current session
  x                      close current
  1-9                    jump to nth tab
  p                      previous session
"
    );
}

fn opt(s: Option<&String>) -> Option<&str> {
    s.map(|s| s.as_str()).filter(|s| !s.is_empty())
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.is_empty() {
        cmd_attach();
        return;
    }
    let cmd = args[0].as_str();
    let rest = &args[1..];
    match cmd {
        "-h" | "--help" | "help" => usage(),
        "render" => {
            let w = rest.first().and_then(|s| s.parse().ok()).unwrap_or(80);
            let cur = rest.get(1).map(|s| s.as_str()).unwrap_or("");
            cmd_render(w, cur);
        }
        "render-msgs" => {
            let w = rest.first().and_then(|s| s.parse().ok()).unwrap_or(80);
            cmd_render_msgs(w);
        }
        "click" => {
            let x = rest.first().and_then(|s| s.parse().ok()).unwrap_or(0);
            let w = rest.get(1).and_then(|s| s.parse().ok()).unwrap_or(80);
            let line = rest.get(3).and_then(|s| s.parse().ok()).unwrap_or(0);
            cmd_click(x, w, opt(rest.get(2)), line);
        }
        "click-close" => {
            let x = rest.first().and_then(|s| s.parse().ok()).unwrap_or(0);
            let w = rest.get(1).and_then(|s| s.parse().ok()).unwrap_or(80);
            let line = rest.get(3).and_then(|s| s.parse().ok()).unwrap_or(0);
            cmd_click_close(x, w, opt(rest.get(2)), line);
        }
        "new" => {
            cmd_new(
                rest.first().map(|s| s.as_str()).unwrap_or(""),
                opt(rest.get(1)),
            );
        }
        "close" => {
            cmd_close(
                rest.first().map(|s| s.as_str()).unwrap_or(""),
                opt(rest.get(1)),
            );
        }
        "rename" => {
            let (old, new_name) = match rest {
                [new_name] => {
                    let old = tmux_stdout(&["display-message", "-p", "#{session_name}"])
                        .trim()
                        .to_string();
                    (old, new_name.as_str())
                }
                [old, new_name, ..] => (old.clone(), new_name.as_str()),
                [] => {
                    eprintln!("tabmux rename: missing new name");
                    std::process::exit(2);
                }
            };
            if old.is_empty() {
                eprintln!("tabmux rename: not inside a tabmux session, pass the old name");
                std::process::exit(2);
            }
            if let Err(e) = cmd_rename(&old, new_name, None) {
                eprintln!("{e}");
                std::process::exit(1);
            }
        }
        "nth" => {
            let i = rest.first().and_then(|s| s.parse().ok()).unwrap_or(0);
            cmd_nth(i, opt(rest.get(1)));
        }
        "menu" => cmd_menu(opt(rest.first())),
        "ls" => cmd_ls(),
        _ => {
            usage();
            std::process::exit(2);
        }
    }
}
